server:
  port: 9988

spring:
  application:
    name: fraud
  datasource:
    username: 'microservices'
    password: 'microservices'
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
